name: Docker Image CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to registry
              uses: docker/login-action@v1
              with:
                  registry: registry.xesacat.xyz
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_KEY }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: registry.xesacat.xyz/yttrium:latest
